language: go

go:
  - 1.3
  - 1.2
  - release
  - tip

install:
  - export LD_LIBRARY_PATH="/usr/local/lib"
  - cd $HOME
  - git clone https://github.com/r9y9/SPTK.git && cd SPTK
  - ./waf configure && ./waf
  - sudo ./waf install
  - cd $TRAVIS_BUILD_DIR
  - go get github.com/mjibson/go-dsp/fft
  - go get github.com/r9y9/go-dsp/wav
  - go get ./...

script:
 - go test ./...
